# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\"\xb8\x01\n\rResponseEntry\x12\n\n\x02id\x18\x01 \x01(\r\x12\x15\n\rtitle_general\x18\x02 \x01(\t\x12\x11\n\tmed_image\x18\x03 \x01(\t\x12\x14\n\x0crating_count\x18\x04 \x01(\r\x12\x14\n\x0crating_value\x18\x05 \x01(\x02\x12\x15\n\rmerchant_name\x18\x06 \x01(\t\x12\r\n\x05value\x18\x07 \x01(\x02\x12\r\n\x05price\x18\x08 \x01(\x02\x12\x10\n\x08\x64iscount\x18\t \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSEENTRY']._serialized_start=19
  _globals['_RESPONSEENTRY']._serialized_end=203
# @@protoc_insertion_point(module_scope)
