# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: titleentry.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10titleentry.proto\"\x9e\x02\n\nTitleEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x61l_id\x18\x02 \x01(\t\x12\x11\n\tdeal_uuid\x18\x03 \x01(\t\x12\x15\n\rtitle_general\x18\x04 \x01(\t\x12\x11\n\tmed_image\x18\x05 \x01(\t\x12\x14\n\x0crating_count\x18\x06 \x01(\r\x12\x14\n\x0crating_value\x18\x07 \x01(\x02\x12\x15\n\rmerchant_name\x18\x08 \x01(\t\x12\x13\n\x0bsmall_image\x18\t \x01(\t\x12\x15\n\rgallery_title\x18\n \x01(\t\x12\x10\n\x08\x63urrency\x18\x0b \x01(\t\x12\x13\n\x0bis_bookable\x18\x0c \x01(\x08\x12\x10\n\x08start_at\x18\r \x01(\t\x12\x0e\n\x06\x65nd_at\x18\x0e \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'titleentry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TITLEENTRY']._serialized_start=21
  _globals['_TITLEENTRY']._serialized_end=307
# @@protoc_insertion_point(module_scope)
