# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idf.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tidf.proto\"%\n\x05NGram\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x02\"g\n\x08IdfEntry\x12\x11\n\tdeal_uuid\x18\x01 \x01(\t\x12\x17\n\x07unigram\x18\x02 \x03(\x0b\x32\x06.NGram\x12\x16\n\x06\x62igram\x18\x03 \x03(\x0b\x32\x06.NGram\x12\x17\n\x07trigram\x18\x04 \x03(\x0b\x32\x06.NGramb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idf_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NGRAM']._serialized_start=13
  _globals['_NGRAM']._serialized_end=50
  _globals['_IDFENTRY']._serialized_start=52
  _globals['_IDFENTRY']._serialized_end=155
# @@protoc_insertion_point(module_scope)
